components.json
jsconfig.json
package-lock.json
package.json
src/components/ui/button.jsx
src/pages/App.jsx
src/styles/index.css
src/utils/utils.js
tailwind.config.js
vite.config.js

Slicing button reusable component DONE

feat(components): add button reusable component

---

src/components/ui/button.jsx
src/pages/App.jsx

Revisi reusable component button supaya dapat menambahkan classname ketika implementasi button

feat(components):revisi code button reusable component

---

src/components/card/CardDashboard.jsx
src/components/ui/card.jsx

add card dashboard reuseable component
use classname props to background and text color

10 slicing card dashboard

---

package-lock.json
package.json
src/components/ui/button.jsx
src/components/ui/calendar.jsx
src/components/ui/form.jsx
src/components/ui/input.jsx
src/components/ui/label.jsx
src/components/ui/popover.jsx
src/pages/module/createMaterial.jsx

SLicing Form tambah modul pada role instruktur :
- Menambahkan package RHF dan zod
- Mengedit variant button
- membuat variant input

feat(modul): Slicing form add modul (Instructor)

---

src/components/rowShow.jsx
src/components/tables.jsx
src/pages/manage-tugas/index.jsx

Halaman Manage Tugas Slicing dan sudah bisa ganti row

feat: add manage tugas

---

.github/workflows/main.yml

change branch name: main to master on workflows

fix: change main to master on workflows

---

src/components/Sidebar/EditProfileSidebar.jsx
src/pages/login/index.jsx

Login Athorization
Handle Logout
https://github.com/HarsaEdu/harsa-frontend/assets/126959335/8cde2016-eb49-4e54-93ab-21cad629b5b4
Feat Add :
- Login Authorization
- Fungsi Handle Logout

feat : add auth login & handle logout

---

package-lock.json
package.json
src/components/inputPassword.jsx
src/components/ui/calendar.jsx
src/pages/admin/user-management/editAkun.jsx
src/pages/admin/user-management/editProfile.jsx
src/pages/admin/user-management/index.jsx

Buat untuk edit akun dan edit profile serta menggunakan dummy data untuk menjadi default value dari inputan. Sudah ada validasinya juga. Dibawah ini ada video demonya

103 slicing edit profile dan edit akun admin

---

src/components/Sidebar/DropdownConfig.jsx
src/pages/manage-faq/manageFaq.jsx
src/routes/index.jsx
src/routes/protectedRoute.jsx
src/utils/dummyData.js

**Slicing kelola FAQ (TABEL)**
[https://drive.google.com/file/d/1UuAUkPBbyfzC-_Bv6VRSHJorWgqXCzU4/view](url)

127 slciing content management faq page

---

src/pages/admin/content-management/kategori/manageCategory.jsx
src/routes/index.jsx
src/routes/protectedRoute.jsx
src/utils/dummyData.js

- Menambahkan tabel kelola kategori
https://github.com/HarsaEdu/harsa-frontend/assets/96949428/e8b5f445-93b6-41d3-afa8-7ba3bf71f447

feat: add table kelola kategori

---

src/pages/notification/index.jsx
src/routes/index.jsx
src/routes/protectedRoute.jsx

Slicing Notification Page
https://github.com/HarsaEdu/harsa-frontend/assets/126959335/e9a3f6a6-6cc0-42be-8f85-045c24ee4d51
- Fitur delete belum berfungsi karena masih ada bug (untuk delete nya menurut saya lebih baik nanti di sempurnakan pada saat sudah terintegrasi dengan API)

feat : slicing notification page

---

src/components/module/materiComponent.jsx
src/pages/admin/content-management/kelas/materiKelas.jsx
src/pages/module/createMaterial.jsx
src/pages/module/updateMaterial.jsx
src/routes/index.jsx
src/routes/protectedRoute.jsx
src/utils/apis/modules/api.js

Link Demo :
https://drive.google.com/file/d/1Rzh9YCqmcv41pLMcHCK9H4amcxlgrNK8/view?usp=sharing
- Overall sudah sesuai untuk create section dan modul
- Sekalian revisi accordion pada edit modul
- Untuk pada halaman edit modul untuk create modul tanpa section tampilan masih belum dinamis, akan dilanjutkan pada update modul task

feat(module): integrasi create modul

---

src/pages/admin/content-management/kategori/addKategori.jsx
src/pages/admin/content-management/kategori/editKategori.jsx
src/pages/admin/content-management/kategori/manageCategory.jsx
src/pages/admin/user-management/editAkun.jsx
src/pages/admin/user-management/editProfile.jsx
src/pages/admin/user-management/tambahUser.jsx
src/pages/admin/userManagement.jsx
src/pages/detail-notifikasi/index.jsx
src/pages/manage-faq/addFaq.jsx
src/pages/manage-faq/editFaq.jsx
src/pages/manage-faq/manageFaq.jsx
src/pages/manage-tugas/editTugas.jsx
src/pages/manage-tugas/reviewTugas.jsx
src/pages/module/createMaterial.jsx
src/pages/module/createTasks.jsx
src/pages/module/updateMaterial.jsx
src/pages/notification/index.jsx
src/routes/index.jsx
src/routes/protectedRoute.jsx

- Add detail notifikasi
- Update pagination

feat : add detail notifikasi

---

src/components/table/tables.jsx
src/pages/admin/pembayaran/riwayatTransaksi.jsx
src/pages/admin/userManagement.jsx
src/utils/apis/payments/api.js
src/utils/apis/user/api.js

- Buat pagination menggunakan response dari API di user management
- membuat fitur search pada user management
- Fixing bug di history payment (salah limit)
Video Demo (user management)
https://drive.google.com/file/d/1gF-DtIjyAI3l8KVlYL2SouYk0PTmlHsw/view?usp=sharing
Video Demo (History Payment)
https://drive.google.com/file/d/1_HRpBg_E0xMRoUfN7kWm3lLlhU4gTMzZ/view?usp=sharing

166 fixing pagination in user management

---

src/pages/admin/pembayaran/riwayatTransaksi.jsx
src/pages/admin/userManagement.jsx

fixing saat pencarian gagal pagination yang masih menampilkan banyak halaman

fix: setMeta on userManagement & riwayatTransaksi

---

src/pages/module/createMaterial.jsx
src/pages/module/formUpdateMaterial.jsx
src/pages/module/updateMaterial.jsx
src/utils/apis/modules/api.js

- Untuk card quiz dan tugas ketika terdapat data quiz dan tugas belum bisa dinamis
- untuk inputan ketika tidak ada perubahan perlu di trigger dengan di beri input terlebih dahulu ( tidak bisa menggunakan default value ketika submit )
- Untuk ketika update, submodule tidak berubah hanya bertambah ( asumsi dari backend ada logic yang salah atau fe salah paham dengan pemberian request )
**Selain case di atas seharusnya berjalan dengan baik**

feat(module): integrasi form update modul

---

src/components/card/cardTugas.jsx
src/pages/admin/content-management/kategori/addKategori.jsx
src/pages/admin/content-management/kategori/editKategori.jsx
src/pages/manage-tugas/editTugas.jsx
src/pages/manage-tugas/index.jsx
src/pages/manage-tugas/listTugas.jsx
src/pages/module/createTasks.jsx
src/pages/module/formUpdateMaterial.jsx
src/routes/index.jsx
src/utils/apis/submission/api.js
src/utils/apis/submission/index.js
src/utils/apis/submissionAnswer/api.js
src/utils/apis/submissionAnswer/index.js

- CRUD Tugas
- List Jawaban Tugas (Submission Answer) Row, Search dan Pagination\
- Form Category Max 10 Character Validation
Video Demo :
https://drive.google.com/file/d/1INVR9Q8OhTh0gTIofYuyc9P5SL-AF0hE/view?usp=sharing
Screenshot Validation

feat: CRUD tugas + max character form kategori (Yang Benar)

---

src/components/breadcrumb.jsx
src/pages/admin/content-management/kelas/materiKelas.jsx
src/pages/admin/dashboard/index.jsx
src/pages/admin/dashboard/tabel/instructorTable.jsx
src/pages/admin/dashboard/tabel/studentTable.jsx
src/pages/admin/user-management/tambahUser.jsx
src/pages/dashboard/card/cardModule.jsx
src/pages/dashboard/card/cardUlasanUser.jsx
src/pages/dashboard/cardTotalMentee.jsx
src/pages/dashboard/index.jsx
src/pages/list-class/index.jsx
src/pages/login/index.jsx
src/pages/module/formKelasAdmin.jsx
src/pages/module/formKelasInstructor.jsx
src/routes/index.jsx
src/utils/apis/auth/api.js
src/utils/apis/auth/index.js
src/utils/apis/dashboard/api.js
src/utils/apis/dashboard/index.js
src/utils/apis/user/api.js
src/utils/apis/user/index.js

integrasi dashboard admin dan instructor
bug fix breadcrumb
config for get access token, ketika access token invalid
fix message error on add user input
fix alert on add course
bug: tabel instructor dan student menggunakan use Params yang sama
video demo di discord

174 integrasi dashboard instructor

---

src/pages/manage-tugas/reviewTugas.jsx
src/pages/module/formUpdateMaterial.jsx
src/pages/module/updateMaterial.jsx
src/utils/apis/submissionAnswer/api.js
src/utils/apis/submissionAnswer/index.js

Link Demo :
https://drive.google.com/file/d/1dXbGbFVCs0WucC1tVi8ne5FG5dPbAMLH/view?usp=sharing
- Yang manage tugas dari form update module sepertinya sudah aman
- yang review tugas tinggal dicoba aja pake data real yang kehubung sama manage tugas

146 integrasi halaman review tugas + fixing manage tugas form update module

---

src/components/ui/calendar.jsx
src/pages/admin/content-management/kategori/addKategori.jsx
src/pages/admin/content-management/kategori/editKategori.jsx
src/pages/admin/content-management/kategori/manageCategory.jsx
src/pages/admin/pembayaran/editSubscription.jsx
src/pages/admin/user-management/detailUser.jsx
src/pages/admin/user-management/editAkun.jsx
src/pages/admin/user-management/tambahUser.jsx
src/pages/module/formEditKelas.jsx
src/utils/apis/manage-category/api.js
src/utils/apis/manage-category/index.js
src/utils/apis/user/api.js

193 revisi user management

---

src/pages/admin/pembayaran/addSubscription.jsx
src/pages/admin/pembayaran/editSubscription.jsx
src/pages/admin/pembayaran/manageSubscription.jsx
src/pages/admin/pembayaran/riwayatTransaksi.jsx
src/pages/list-class/CardListClass.jsx
src/pages/list-class/index.jsx
src/pages/manage-tugas/listTugas.jsx
src/pages/tambah-kuis/cardQuiz.jsx
src/pages/tambah-kuis/header.jsx
src/pages/tambah-kuis/index.jsx
src/pages/tambah-kuis/jawabanKuis.jsx
src/routes/index.jsx
src/utils/apis/courses/api.js
src/utils/apis/historyQuiz/api.js
src/utils/apis/historyQuiz/index.js
src/utils/apis/quiz/api.js
src/utils/apis/quiz/index.js
src/utils/apis/submission/api.js
src/utils/apis/subs-plan/api.js

- Integrasi Filter Kategori & Search di List Class 
Video Demo : https://drive.google.com/file/d/14GvhMT1O4EZZ3L1vuRKj5ZENkMTGOlDn/view?usp=sharing
- Fixing Pagination, Row dan search di langganan (subs plan)
Video Demo : https://drive.google.com/file/d/1mJeSy115qR-rwa8h-Nk0uTLO4l1hZU3d/view?usp=sharing
- integrasi list quiz dan jawaban quiz by id (bug : list quiz belum sesuai modul)
Video Demo : https://drive.google.com/file/d/1y8taA6wiIyHoQcb7Kc6HbhGIsk6ssgEL/view?usp=sharing

189 integrasi jawaban quiz

---

src/pages/admin/pembayaran/riwayatTransaksi.jsx
src/pages/manage-faq/addFaq.jsx
src/pages/manage-faq/editFaq.jsx
src/pages/manage-faq/manageFaq.jsx
src/pages/tambah-kuis/jawabanKuis.jsx
src/utils/apis/payments/api.js

fixing bug di FAQ
- Fungsi tombol batal di create FAQ
- pesan error di edit yang tidak berfungsi ketika inputan kosong
- delete FAQ
Membuat export ke CSV untuk riwayat transaksi dan jawaban kuis
Video Demo (minus export jawaban kuis)
https://drive.google.com/file/d/1H7GicvXnP6KClDnuCUVcx63zfLp5oHgr/view?usp=sharing
[example jawaban-kuis (1).csv](https://github.com/HarsaEdu/harsa-frontend/files/13695138/example.jawaban-kuis.1.csv)
[example riwayat-transaksi.csv](https://github.com/HarsaEdu/harsa-frontend/files/13695139/example.riwayat-transaksi.csv)

200 fixing faq, export jawaban kuis and history payment

---

src/pages/detail-notifikasi/index.jsx
src/pages/notification/index.jsx
src/routes/index.jsx
src/utils/apis/notification/api.js

Integrasi Notifikasi
video demo :
https://drive.google.com/file/d/1R4MhxsQaw0g6hatMEPTVX83gF6Sskjlf/view?usp=drive_link

feat : integrasi notifikasi

---

src/pages/admin/pembayaran/manageSubscription.jsx

fix popup delete
https://github.com/HarsaEdu/harsa-frontend/assets/126959335/7f875d6b-8bd8-42d6-83c5-3099b0608c12

feat : fix popup delete

---

src/components/card/cardModule.jsx
src/components/module/dialogAddUser.jsx
src/pages/admin/content-management/kelas/assignUser.jsx
src/pages/assign-users/assignUserInstruktor.jsx
src/pages/manage-tugas/listTugas.jsx
src/utils/apis/courseTrackingWeb/api.js

- get subscriber class
- enroll subscriber
- delete enroll subscriber

feat: add asign user subscriber

---

src/pages/module/createMaterial.jsx
src/pages/module/formUpdateMaterial.jsx
src/pages/module/updateMaterial.jsx

- Tambah Module
- Update Module
- Sudah solve validation nya judul materi di update dan link materi di semua form modul
- Semoga sudah solve semua case :))

Fixing validation form module

---

src/pages/admin/content-management/kelas/cardUlasanKelas.jsx
src/pages/module/ManageKelas.jsx
src/routes/index.jsx

1. Integrasi Get Feedback
2. Integrasi Delete Feedback
https://github.com/HarsaEdu/harsa-frontend/assets/139904549/a21da34e-58fa-4543-84fa-22c6aacd053f

192 integrasi ulasan

---

src/pages/admin/pembayaran/addSubscription.jsx
src/pages/admin/pembayaran/editSubscription.jsx
src/utils/apis/subs-plan/api.js
src/utils/apis/subs-plan/index.js

**Fix Bug**
- Image tidak harus di isi saat edit
- validasi tidak muncul ketika image tidak di isi ulang
- update image sudah berjalan
https://drive.google.com/file/d/1J0LxRYLbx4NCUVE6aDzNQiEL20zpDrz7/view?usp=sharing
*itu bagian pas buka file nya ga ke record aslinya ada kok

feat: fix bug image edit langganan page

---

src/pages/list-class/CardListClass.jsx
src/pages/module/ManageKelas.jsx
src/pages/module/formEditKelas.jsx

- Update Edit Kelas (menambahkan role agar tampilan UI nya sesuai)
Role Admin
Role Instructur
- Delete Button Edit Pada Manage Kelas (icon Pensil)
- Menambah fungsi untuk judul pada Card List Kelas menjadi maks. 30 karakter

feat : update editKelas, CardListKelas, ManageKelas

---

src/pages/module/formUpdateMaterial.jsx
src/pages/tambah-kuis/editQuiz.jsx
src/pages/tambah-kuis/headerCreate.jsx
src/pages/tambah-kuis/index.jsx
src/pages/tambah-kuis/questionCard.jsx
src/routes/index.jsx
src/utils/apis/quiz/api.js
src/utils/apis/quiz/index.js

feat: integrasi quiz
